# Generated by Django 2.2.13 on 2020-06-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200617_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
