# Generated by Django 2.2.13 on 2020-07-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyskill',
            name='text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
