# Generated by Django 2.2.13 on 2020-07-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_year',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
