# Generated by Django 2.2.13 on 2020-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
