# Generated by Django 2.2.13 on 2020-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
