# Generated by Django 2.2.13 on 2020-07-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_auto_20200714_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
